import os
from urllib.parse import urlparse
from instaloader import Instaloader, Post, Profile


def extract_username(value: str) -> str:
	value = value.strip()
	if value.startswith("http"):
		parsed = urlparse(value)
		path = parsed.path.strip("/")
		if not path:
			raise ValueError("Couldn't extract username from URL")
		return path.split("/")[0]
	return value


def extract_shortcode(url: str) -> str:
	url = url.strip()
	if not url.startswith("http"):
		return url  # assume it's already shortcode
	parsed = urlparse(url)
	path = parsed.path.strip("/")
	if path.startswith("reel/"):
		return path.split("reel/")[1].split("/")[0]
	elif path.startswith("p/"):
		return path.split("p/")[1].split("/")[0]
	else:
		raise ValueError("Invalid Instagram post/reel link")


def delete_related_files(basepath):
	exts = [".jpg", ".txt", ".json.xz", ".json", ".webp", ".mp4"]
	for ext in exts:
		f = basepath + ext
		if os.path.exists(f):
			try:
				os.remove(f)
			except Exception:
				pass
	# Also delete thumbnail generated by instagrapi: <basename>.mp4.jpg
	thumb = basepath + ".mp4.jpg"
	if os.path.exists(thumb):
		try:
			os.remove(thumb)
		except Exception:
			pass


def download_single_reel(L, shortcode, dest="downloads"):
	"""Download a single reel by shortcode."""
	try:
		post = Post.from_shortcode(L.context, shortcode)
	except Exception as e:
		print("Failed to load post:", e)
		return None

	print("Downloading the reel...")
	L.download_post(post, target="reel_download")

	base = os.path.join(dest, "reel_download", f"{post.date_utc.strftime('%Y-%m-%d_%H-%M-%S_UTC')}")
	mp4_path = base + ".mp4"

	if os.path.exists(mp4_path):
		return mp4_path, post.caption or ""
	else:
		print("Video file not found")
		return None


def download_profile_reels(L, profile_username, dest="downloads", start=0, end=None):
	"""Download reels from a profile in range, return list of (mp4_path, caption)."""
	try:
		profile = Profile.from_username(L.context, profile_username)
	except Exception as e:
		print("Failed to load profile:", e)
		return []

	videos = []
	count = 0
	for post in profile.get_posts():
		if getattr(post, 'is_video', False):
			count += 1
			if count < start:
				continue
			if end and count > end:
				break
			print(f"Downloading reel {count}: {post.shortcode}")
			L.download_post(post, target=profile_username)

			base = os.path.join(dest, profile_username, f"{post.date_utc.strftime('%Y-%m-%d_%H-%M-%S_UTC')}")
			mp4_path = base + ".mp4"

			if os.path.exists(mp4_path):
				videos.append((mp4_path, post.caption or ""))
			else:
				print(f"Video file not found: {mp4_path}")

	return videos


def download_profile(L, profile_username):
	"""Download entire profile."""
	L.download_profile(profile_username, profile_pic_only=False)
	print("Download completed.")